version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: mqtt-project-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    restart: always
    networks:
      - mqtt-project-network

networks:
  mqtt-project-network:
    external: true